broker = "bemfa.com"
port = 9501
test = 0
auth_mode = "private_key"
mqtt_username = ""
mqtt_password = ""
client_id = "********"
Computer = "dnkz006"
Computer_checked = 1
screen = "dnpm002"
screen_checked = 1
volume = "dnyl009"
volume_checked = 1
sleep = ""
sleep_checked = 0
media = "mtkz009"
media_checked = 1
computer_on_action = "lock"
computer_off_action = "shutdown"
computer_on_delay = 0
computer_off_delay = 0
sleep_on_action = "none"
sleep_off_action = "none"
sleep_on_delay = 0
sleep_off_delay = 0
notify = 0
brightness_mode = "custom"
twinkle_tray_path = "C:/Program Files/WindowsApps/38002AlexanderFrangos.TwinkleTray_2025.11225.11438.0_x64__m7qx9dzpwqaze/app/Twinkle Tray.exe"
twinkle_tray_target_mode = "all"
twinkle_tray_target_value = "0"
twinkle_tray_overlay = 1
language = "zh"
mqtt_tls = 0
mqtt_tls_verify = 0
mqtt_tls_ca_file = ""
brightness_custom_list = "wmi,dxva2"
brightness_custom_strategy = "all"
wmi_target = "all"
dxva2_target = "all"
application1 = "tsml006"
application1_name = "特殊目录"
application1_checked = 1
application1_directory1 = "D:/Code/Python/Special-Folders/dist/特殊文件夹.exe"
application1_on_value = "D:/Code/Python/Special-Folders/dist/特殊文件夹.exe"
application1_off_value = ""
application1_off_preset = "kill"
application2 = "yxms006"
application2_name = "启动器"
application2_checked = 1
application2_directory2 = "D:/Otheapps/Starward/Starward.exe"
application2_on_value = "D:/Otheapps/Starward/Starward.exe"
application2_off_value = ""
application2_off_preset = "kill"
application3 = "uuyc006"
application3_name = "UU远程"
application3_checked = 1
application3_directory3 = "C:/Program Files/Netease/GameViewer/GameViewer.exe"
application3_on_value = "C:/Program Files/Netease/GameViewer/GameViewer.exe"
application3_off_value = ""
application3_off_preset = "kill"
application4 = "xyzbz006"
application4_name = "播放视频"
application4_checked = 1
application4_directory4 = "D:/Code/View/view.ps1"
application4_on_value = "D:/Code/View/view.ps1"
application4_off_value = ""
application4_off_preset = "kill"
serve1 = "uuyckzfw006"
serve1_name = "UU远程控制服务"
serve1_checked = 1
serve1_value = "GameViewerService"
serve1_on_value = "GameViewerService"
serve1_off_value = ""
serve1_off_preset = "stop"
command1 = "ml006"
command1_name = "命令"
command1_checked = 1
command1_value = "cmd /v:on /c \"for /l %n in (1,1,999999) do @echo %n\""
command1_on_value = "cmd /v:on /c \"for /l %n in (1,1,999999) do @echo %n\""
command1_off_value = "cmd /v:on /c set"
command1_off_preset = "custom"
command1_window = "show"
command1_value_min = 0
command1_value_max = 100
command2 = "cscs002"
command2_name = "测试参数"
command2_checked = 1
command2_value = "echo {value}"
command2_on_value = "echo {value}"
command2_off_value = ""
command2_off_preset = "kill"
command2_window = "show"
command2_value_min = 0
command2_value_max = 10000
command3 = "bfsb006"
command3_name = "播放设备"
command3_checked = 1
command3_value = "powershell -ExecutionPolicy ByPass -File \"d:\\Code\\PowerShell\\audio.ps1\""
command3_on_value = "powershell -ExecutionPolicy ByPass -File \"d:\\Code\\PowerShell\\audio.ps1\""
command3_off_value = "powershell -ExecutionPolicy ByPass -File \"d:\\Code\\PowerShell\\Set-AudioDevice.ps1\" -NameLike \"HECATE G2无线版\""
command3_off_preset = "custom"
command3_window = "hide"
command3_value_min = 0
command3_value_max = 100
hotkey1 = "xhy006"
hotkey1_name = "小黄鸭"
hotkey1_checked = 1
hotkey1_on_type = "keyboard"
hotkey1_on_value = "ctrl+alt+s"
hotkey1_off_type = "keyboard"
hotkey1_off_value = "ctrl+alt+s"
hotkey1_char_delay_ms = 25
hotkey2 = "gbyy006"
hotkey2_name = "当前应用"
hotkey2_checked = 1
hotkey2_on_type = "none"
hotkey2_on_value = ""
hotkey2_off_type = "keyboard"
hotkey2_off_value = "alt+f4"
hotkey2_char_delay_ms = 25
